### PR TITLE
Make area designation step multi-tile, #879

### PR DESCRIPTION
**Pull request by njkim**
Update app area workflow area designation step to a multi-tile step, #879

### CODE REVIEW

**Review by chiatt — CHANGES_REQUESTED** [review]
This looks good @njkim, but the final step shows only the first of the designations if there is more than one.

**Comment by njkim** [comment]
> the final step shows only the first of the designations if there is more than one.

Ah, good catch! thanks. I am looking into it.

**Comment by njkim** [comment]
> This looks good @njkim, but the final step shows only the first of the designations if there is more than one.

The summary step is updated. Also, all other visible nodes in the summary are added, too.

**Review by chiatt — APPROVED** [review]

**Review by chiatt — APPROVED** [review]
Looks great!

**Pull request merged**
