### PR TITLE
Fixes and features to arches-her following Keystone release

### LINKED ISSUE #918: Reports: Multiple resources - Citations not displaying in Descriptions and Citations tab
**Issue Description** - In the report templates - Citations are not displaying in the Descriptions and Citations tab.

Effecting the following models:
- Heritage Story
- Aircraft
- Maritime 

**Steps to reproduce**

1) Open an Aircraft record in report mode

2) Click on the Descriptions and Citations tab

3) Only Descriptions are displayed in the report tab - 

Citations should also display 

image

### LINKED ISSUE #964: Letters - (logic) duplicate salutation when person has an existing title
**Issue description** - When a person has an existing title e.g., Miss or Mr, this then duplicates in the generated Corresspondence letters, so the person title is displayed twice.

**Steps to reproduce**

1) Open a new Corresspondence workflow

2) Search for and select a Consultation record that has a Person record with an exisiting title selected as the contact point for corresspondence e.g., Mr Joe Bloggs

3) Select Letter A  - No Progression as the Letter Type

4) Save the step and once loaded, download the generated letter from the download link

5) Open the letter - the salutation has been duplicated

Examples - 

image

image

### LINKED ISSUE #965: Letters - (formatting) WSI Approval WSI Amend condition type not needed
**Issue description** - In the WSI Approval, WSI Amend letters, the Condition Type value is not needed as the letters already state that we are approving the WSI, so having the Condition Type in the letter is redundant.

Remove the <Condition Type>, but keep the <Condition> text.

**Steps to reproduce**

1) Open a new Correspondence workflow

2) Select a related Consultation

3) Select Letter F1 - WSI Approval as the letter, or Letter F2 - WSI Amend

4) Save and download the letter from the link on the next step

5) Open the letter - the Condition Type and Condition text are present in the letter

Remove Condition Type (Agree WSI and Amend WSI) but keep the condition text added by the user.

**WSI Approval -**
image

**WSI Amend -** 
image

### LINKED ISSUE #966: Letters - (logic) - the value 'none' appears when no text is added to Action
**Issue description** - When there is no text added to the Action (mitigation) and there is only an Action Type, the Action Type appears in the letter with 'None' next to it. 

Still include the scope note from mitigation scope note ticket

**Effected letters**

- Pre-app predetermination EAS version
- Predetermination 
- Condidtion two stage
- Pre-app reccomend condition EAS version
- Condition investigation
- Condition historic building recording

**Steps to reproduce**

1) Open a new Correspondence workflow

2) Select a related Consultation

3) Select Letter B2 - Predetermination as the letter

4) Save and download the letter from the link on the next step

5) Open the letter and scroll to the Recommendations section - the Action Type value 'Desk Based Assessment' is displayed with the word None at the end. This should be removed so only the Action Type is displayed.

If Action text is added this will replace the None placeholder.

image

image

### LINKED ISSUE #968: Letters - (logic) Only one 'Advice' is displaying in letters
**Issue description** - Only one Advice (Condition) is displayed in letters.

**Expected result** - if a Consultation has multiple Advice nodes they should all display in the specified letters.

**Effected letters**

- Condition Satisfied 
- Post Evacuation Assessment Approval
- WSI Amend 
- WSI Approval
- 

**Steps to reproduce**

1) Open a new Corresspondence workflow

2) Search for and select a related Consultation with multiple Adivce nodes

3) Select WSI Approval as the Letter Type

4) Save and move to the next step

5) Download and open the letter - only one Advice is shown in the letter but the Consultation record has multiple:

image

image

### LINKED ISSUE #970: Letters - (formatting and logic?) Double spacing should be a single space
**Issue description** - In some of the letter templates, there is a two line gap under the line 'The archaeological work should include' and before the Action Type text - this should only be a single line as it is below the Action Type text.

**Effecting the following letters**

- Condition Historic Building Recording
- Condidtion Investigation

**Steps to reproduce**

1) Open a new Correspondence workflow

2) Search for and select a related Consultation with Actions added

3) Select Letter D3 - Condition Historic Building Recording as the letter

4) Save and download the letter from the link on the next step

5) Open the letter - scroll down to this section:

The highlight is where the double spacing is

image

### LINKED ISSUE #971: Letters - (formatting) Bespoke letter should be blank
**Issue description** - Letter I - Bespoke Letter currently contains text that should not be there - this letter should only contain the Consultation Name and Proposal.

**Steps to reproduce**

1) Open a new Correspondence workflow

2) Select a related Consultation

3) Select Letter I - Bespoke Letter as the letter

4) Save and download the letter from the link on the next step

5) Open the letter - template currently contains other text and conditions - need to confirm what the letter should actually contain

image

### LINKED ISSUE #972: Letters - (formatting) All font should be Source Sans Pro Light (except signature)
**Issue description -** ALL fonts except the signature must be Source Sans Pro Light. 

The signatures (name at end) should be Source Sans Pro (not light).

**Steps to reproduce**

1) Open a new Correspondence workflow

2) Select a related Consultation

3) Select Letter A - No Progression as the letter

4) Save and download the letter from the link on the next step

5) Open the letter - the highlighted text is in Source Sans Pro and should be Source Sans Pro Light like the surrounding text 

image

### LINKED ISSUE #974: Letters - (formatting) Email should display on single line
**Issue description** - In all letter templates, the contact email covers two lines.

**Steps to reproduce**

1) Open a new Correspondence workflow

2) Select a related Consultation

3) Select Letter A - No Progression as the letter

4) Save and download the letter from the link on the next step

5) Open the letter - Person contat email is on two lines

image

**Expected result** - the email should be on the same line.
image

Make top two column equal width, font size 10, and adjust format/field names to match below:
image

### LINKED ISSUE #1015: Post-Go Live Keystone Giveback Items
This is a catch-all issue ticket for bug fixes/changes made to arches-her after the initial release of Keystone.

### PR DESCRIPTION
**Pull request by aj-he**
- Corrections to letter text
- Added scope notes to letters that have advice tags
- Added sort by Target date to Active Consultations
- Missed corrections to reports following graph renaming change.
- Missed corrections to HTML export templates following graph renaming 

fixes #1015
fixes #968 
fixes #966
fixes #964 
fixes #970
fixes #974 
fixes #972
fixes #918
fixes #965
fixes #971

### CODE REVIEW

**Comment by csmith-he** [comment]
Hi @njkim; who out of the core Arches team are able to review this PR please?

**Comment by njkim** [comment]
@csmith-he I will take a look at this. thanks.

**Comment by csmith-he** [comment]
@njkim - That's great.  Cheers, Namjun.  If you have any questions or need clarification on anything then just give me a shout.

**Review by njkim — APPROVED** [review]
Looks good to me.

**Pull request merged**
